export const SCREEN_NAMES = {
  HOME_SCREEN: 'HOME_SCREEN',
  SUBSCRIPTION_SCREEN: 'SUBSCRIPTION_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
};

export const STACK_NAMES = {
  HOME_STACK: 'HomeStack',
  SETTING_STACK: 'SettingStack',
};

